### ISSUE TITLE
homebutton doesn't work in learning section

### ISSUE THREAD

**Issue by willGG11** [wordplaydev/wordplay#197] opened 2023-10-11 01:35 UTC
## Expected behavior

click homebutton should navigate directly to the home page

## Actual behavior
It actually backward the slides. However, the forward button turns orange.

1. Go to 'learn' section
2. Click on 'forward' button
3. Click home button multiple times

## Screenshots

<img width="1436" alt="截屏2023-10-10 18 33 10" src="https://github.com/wordplaydev/wordplay/assets/106497657/c5fcdf7a-0a57-48ff-8dd2-b93a30c961e4">

## Environment

What platform, OS, browser, and version are you using?
-Desktop
Mac OS on Edge Browser
version  117.0.2045.55

**Comment by amyjko** [comment] 2023-10-11 02:14
I can't reproduce this on Edge on mac OS. Can clarify a few things?

* What is the "error" referred to in the repro steps above?
* Does "home button" refer to the button in the bottom left of the tool bar?
* What does it mean to press it multiple times?
* Can you show a screenshot of the error?

Pressing it once goes home, pressing it multiple times does nothing for me, since the button is disabled on the home screen.

**Comment by amyjko** [comment] 2023-10-14 14:46
@willGG11 Can you please answer the questions above, so we can reproduce and fix this?

**Comment by amyjko** [comment] 2023-10-14 22:42
I believe this was the behavior prior to 1eb2bf0, when the home button used to be a back button. After that commit, the home button was an explicit home button. I suspect this issue was filed on an old version.

Closing for now, but if you're still seeing this after updating your local repro to the latest branch, reopen it.

**Closed by amyjko** 2023-10-14 22:42 UTC
Labels: defect, needs repro

**Comment by willGG11** [comment] 2023-10-14 22:50
Sorry Amy,
I thought I updated the GitHub issues last Thursday. Now I realize I didn't
post it due to switching wifi from school to my home :(
Sorry for the inconvenience.
