### ISSUE TITLE
Chinese signs cannot be recognized.

### ISSUE THREAD

**Issue by ShufaW** [wordplaydev/wordplay#532] opened 2024-07-19 00:07 UTC
### What are you trying to do that you can't?

For example, when I try to type "Stage([Shape(Circle(1m 0m 0m))])" in Chinese, it becomes "舞台([形状(圆圈(1m 0m 0m))])". However, I must use the English punctuation marks like "(", and ")", instead of the Chinese versions "（", and "）", because the Chinese punctuation marks are not recognized. This makes it challenging for users in non-English environments, as they need to spend considerable time converting punctuation marks between languages.

### What is your idea?

Is it possible to improve software localization to recognize and interpret different punctuation marks and symbols based on the user's language settings. This would allow users to use their native signs without issues. Or there could have more shortcuts for more frequently used signs?

**Comment by amyjko** [comment] 2024-07-22 21:40
It is definitely possible to support Chinese parentheses. (I didn't even realize they were different!) Do you have a list of punctuation equivalents, other than parentheses, that need to be supported? Here's the list so far.

```
（
）
```

**Comment by amyjko** [comment] 2024-07-22 21:42
I see a list of full-width punctuation equivalents here:

https://en.wikipedia.org/wiki/Chinese_punctuation

Is that a good list of Unicode symbols to define as equivalents?

**Comment by ShufaW** [comment] 2024-07-23 08:51
Yes, I think this is a professional list.

**Comment by ShufaW** [comment] 2024-07-23 18:11
Yes sure! I can implement this.

**Comment by amyjko** [comment] 2024-07-23 20:23
The key place to look is `Tokenizer.ts`. There you'll see a list of token definitions, such as the one defined for `Sym.EvalOpen` and `Sym.EvalClose`. Those define strings or regular expressions that define particular token types. You'll want to create additional entries in this list, likely right next to the corresponding tokens (order matters), having those new Unicode full-width versions also count as the same token types. The pull request should also add test cases to `Tokenizer.test.ts` to ensure that they tokenize correctly, at least one for each added symbol.

**Comment by lpjjj1222** [comment] 2024-10-16 22:45
Hi Amy @amyjko , I would like to request to be assigned to this issue, following the instruction given above to fixed this locale problem.

**Comment by lpjjj1222** [comment] 2024-10-18 01:16
Oh amy, I guess you assigned the wrong guy🤣

**Comment by amyjko** [comment] 2024-10-18 05:19
Oops, fixed.

**Comment by lpjjj1222** [comment] 2024-11-06 23:36
@amyjko Hi Amy, seems like this issue already been fixed by someone else. Since I attempted to reproduce the issue description and found that the Chinese symbols were successfully recognized.

**Comment by amyjko** [comment] 2024-11-08 00:46
@lpjjj1222 Thanks for letting me know; it's possible the issue was closed but the commits didn't reference this issue. I'll close since you can't reproduce.

**Closed by amyjko** 2024-11-08 00:46 UTC
Labels: enhancement, language, starter, buildable
