### ISSUE TITLE
Local emulator cannot be used by contributors without access to the Firebase project

### ISSUE THREAD

**Issue by shiinasugioka** [wordplaydev/wordplay#318] opened 2023-12-06 02:10 UTC
## Expected behavior

The command `npm run emu` should allow users to run the Firebase Emulator.

## Actual behavior

When user uses the command, error message pops up: `Error: Invalid project selection, please verify project dev exists and you have access.`

## Screenshots

![image](https://github.com/wordplaydev/wordplay/assets/91639423/0c608172-c092-4cd6-92af-ed7469f0d39c)
![image](https://github.com/wordplaydev/wordplay/assets/91639423/be8da9d0-9952-45af-96a6-80ffed3e5dfb)

## Environment

Using windows 11
Logged into emulator using @uw.edu email

**Comment by shiinasugioka** [comment] 2023-12-07 20:29
Additional notes:

**Comment by amyjko** [comment] 2023-12-08 02:06
Fixed vague issue title. Make sure to write issue titles that precisely describe the problem (e.g., don't use "issue" to describe an issue, say what the issue is).

**Comment by amyjko** [comment] 2023-12-08 03:04
@shiinasugioka It looks like the Firebase documentation on this is pretty sparse, but I think I figured it out.

* You can run `firebase emulators:start` without having access to the `wordplay-dev` project
* You can't do `firebase use dev` without access to the `wordplay-dev` project

Can you try just doing `firebase emulators:start` and see if that works? You'll also want to be running the vite dev server, `npm run dev`. If you can confirm it does, I'll update the wiki documentation and close this issue.

**Comment by shiinasugioka** [comment] 2023-12-08 03:59
@amyjko I tried `firebase emulators:start` and `firebase use dev` (see second screenshot in original post).

**Comment by amyjko** [comment] 2023-12-08 04:34
@shiinasugioka Ah, missed that. I tried a clean repo on my end with a different firebase account without permissions and just doing `firebase use` seems to work to select the default active project, even though `firebase use dev` does not. Try that, then `firebase emulators:start`?

**Comment by amyjko** [comment] 2023-12-09 19:36
@shiinasugioka I believe removing `dev` from the firebase command resolves this; it did when I tried it on a fresh install. Reopen if it doesn't and we'll keep troubleshooting.

**Comment by shiinasugioka** [comment] 2024-01-08 03:56
@amyjko  Hello! Sorry for the late response, I was abroad over winter break and didn't have to capacity to look through my emails. Regarding the command, someone else on discord messaged me saying they were running into the same issue and the command `firebase use` did not work for them. I tested this on my end as well and got the following result:
![image](https://github.com/wordplaydev/wordplay/assets/91639423/57769832-ade3-49c9-af12-eb1294ef4c69)

**Comment by amyjko** [comment] 2024-01-09 16:16
Thanks for reopening. It looks like we have some more to learn about how to enable contributors to use the emulator without being added as a collaborator on the Firebase project. I'll see if I can dig deeper on documentation on this use case.

**Comment by amyjko** [comment] 2024-01-10 02:41
I think I found the (very hidden) docs on how to do this. There's a way to point the emulator to a fake project by just prefixing the project id with `demo-`:

https://firebase.google.com/docs/emulator-suite/connect_auth

I've updated the `npm run emu` command to do this instead of pointing to the very real `wordplay-dev` project. I tested this on a fresh install on a different machine and it appears to work. Test, and if it doesn't for you, feel free to reopen.

**Closed** 2024-01-10 02:42 UTC
Labels: defect, maintainability
