### ISSUE TITLE
Issue with scoring in the basketball game

### ISSUE THREAD

**Issue by MichelleGuan1128** [wordplaydev/wordplay#358] opened 2024-01-25 01:55 UTC
## Expected behavior

Expect to earn a score when the basketball is in the hoop.

## Actual behavior

Provide detailed steps that consistently reproduce the behavior, including any example code. If you can, make the steps as minimal as possible, finding the smallest possible set of steps that still produce the unexpected behavior.

1. Go to 'Galleries'
2. Click on 'Games'
3. Scroll down to 'Basketball Star'

## Screenshots
<img width="1440" alt="Screenshot 2024-01-24 at 5 49 08 PM" src="https://github.com/wordplaydev/wordplay/assets/76934364/54137993-5fe9-4aea-b7bf-1d45526d8d93">

<img width="863" alt="Screenshot 2024-01-24 at 5 50 41 PM" src="https://github.com/wordplaydev/wordplay/assets/76934364/4aa5f85e-0b39-4ecb-a868-e6095f8b9822">

Did not earn a score when the basketball is in the hoop. Sometimes it earns a score even if the basketball is not in the hoop. 

## Environment

What platform, OS, browser, and version are you using? Please be exact with version numbers, as different versions can result in a defect happening or not. Don't skip these; cross-browser issues are a common cause of problems.

Desktop
Device: MacBook Pro Intel Core i5
OS: MacOS 14.0
Browser FireFox
Version 118.0.2

**Comment by amyjko** [comment] 2024-01-26 01:25
Thanks for reporting @MichelleGuan1128! Want to try to fix it?

**Comment by jianna-braza** [comment] 2024-02-01 01:57
hello! quick question about this issue: is this something I am fixing within wordplay itself or vscode? Is the goal of this issue to fix the current code within wordplay like what is displayed below?

<img width="744" alt="image" src="https://github.com/wordplaydev/wordplay/assets/91649104/f6595e2e-c289-4153-8182-7ab80d883011">

Thank you!

**Comment by amyjko** [comment] 2024-02-02 04:47
@jianna-braza That's a good question for @MichelleGuan1128. The issue reported is with the logic of the game, not Wordplay, but it may be caused by something in Wordplay (e.g., limitations of the physics engine being used). Your job is to figure out which it is.

**Comment by amyjko** [comment] 2024-03-15 03:38
It's the end of Winter! Please provide an update on this issue, including:

* Whether you plan to continue work on it
* If you do not, 1) provide a detailed update of its status, 2) add any unfinished work, 3) list any any unmerged branches, and 4) unassign yourself, so someone else can take over the task. Please leave the issue in better shape than you found it, helping future contributors to start from where you left off.

If you do plan to continue work on it, carry on. Otherwise, thank you for your contributions!

**Comment by amyjko** [comment] 2024-03-26 16:10
No reply :( Unassigning @jianna-braza.

**Comment by nAtHanDang0703** [comment] 2024-05-16 18:21
I've managed to make the scoring pretty accurate. Sometimes, the score wouldn't go up if the ball touches the rim and rolls into the basket.

**Comment by amyjko** [comment] 2024-05-16 18:32
I see this as closed, but I don't see a pull request for it. (The process is that you make a commit in a branch that as "Fixed #358", submit a PR, I review it, and then merge once it's done).

**Comment by nAtHanDang0703** [comment] 2024-05-16 18:38
That's my bad, I'm creating a PR right now.

**Comment by amyjko** [comment] 2024-05-19 21:43
Resolved by #468.

**Closed by amyjko** 2024-05-19 21:43 UTC
Labels: defect, starter, example
