### ISSUE TITLE
All Table of Contents Default to Fullscreen Silence 

### ISSUE THREAD

**Issue by EddieNew** [wordplaydev/wordplay#225] opened 2023-10-25 01:27 UTC
## Expected behavior

When clicking through the pages of Learn in the table of contents, the expected behavior is to move to the correct page, with the character text boxes and arrows readily available. 

## Actual behavior

When clicking on any table of contents section, it moves to the "silence" page of the Verse chapter, and full-screens the workspace. This results in an all-black screen, and it was initially unclear that I needed to exit fullscreen to continue.  

Outside of the table of contents, using the arrows to navigate to page 1 and page 7 of the Verse chapter also cause this, and I am unable to move past page 7. Clicking the arrows after exiting fullscreen just opens it back up, and navigates back to page 7 again. This issue may or may not exist elsewhere. 

## Screenshots

<img width="1440" alt="Screenshot 2023-10-24 at 6 15 17 PM" src="https://github.com/wordplaydev/wordplay/assets/92896893/3868d62d-0d86-44c9-83f7-04a517f19d33">

<img width="1438" alt="Screenshot 2023-10-24 at 6 24 27 PM" src="https://github.com/wordplaydev/wordplay/assets/92896893/d058d9a0-3ac0-4331-bf66-18cd080d497e">

## Environment

Macbook Air M1 Laptop

-   macOS 13.5
-   Chrome Version 117.0.5938.149

**Comment by amyjko** [comment] 2023-10-25 15:25
Duplicate of #223. I'll keep this open for now, since it has better details.

**Closed** 2023-10-25 16:24 UTC
Labels: defect, projects
